# Bookdown


R proj particulier pour le bookdown 

## Fichiers particuliers
+ index.rmd : fichier pour indiquer le header de ts les fichiers, écrit la "préface"

+ _bookdown.yml : def construction livre
```{r, eval = F}
book_filename: "My_cours"
delete_merged_file: true # supprimer le fichier intermediaire de la compilation
language:
  ui:
    chapter_name: "Cours "
output_dir: "docs" # dossier de stockage de la compilation
```

+ _output.yml : def construction des sorties
```{r, eval = F}
bookdown::gitbook:
  config:
    toc:
      before: |
        <li><a href="./">My_cours</a></li>
      after: | # lien "source" vers le dépot Github
        <li><a href="https://github.com/VincyaneBadouard/My_cours" target="blank">Source</a></li>
      collapse: section # pour ne pas afficher les sous-parties ds le menu deroulant
  includes:
    in_header: hypothesis.html # permet les comentaires dans le doc (open review)
    before_body: open_review_block.html
```
scroll_hillight: yes # mise en couleur qd on est dans la partie
