# Distinction britanique/americain

Règle générale : Le britanique a gardé l'orthograohe originale des mots alors que l'américain préfère une orthogrophe plus proche de la prononciation.  

## -our (UK) ou -or (US)

Souvent les mots terminant par -eur en français  

ex: colour/color, favour/favor, humour/humor, labour/labor, favourite/favorite, neighbour/neighbor  

## -re (UK) ou -er (US)

Souvent les mots terminant par -re en français  

ex: centre/center, kilometre/kilometer, metre/meter  

## -ise (UK) ou -ize (US)

Généralement des verbes  

ex: organise/organize, apologise/apologize, recognise/recognize  

## -nce (UK) ou -nse (US)

ex: defence/defense, licence/license, offence/offense  

## -ge (UK) ou -g (US)

ex: judgement/judgment, ageing/aging, arguement/argument  

## -ae (UK) ou -e (US)

ex: encyclopeadia/encyclopedia, orthopeadics/orthopedics, aeon/eon, mediaeval/medieval, manoeuvre/maneuver  

## -ogue (UK) ou -og (US)

ex: analogue/analog, catalogue/catalog, dialogue/dialog  

## -que (UK) ou -ck (US)

ex: cheque/check, chequer/checker  

## voyelle + L

Verbes qui se terminent par une voyelle suivie de la lettre L à l'infinitif, dans leurs formes plus longues (conjuguées ou substantivées), les Anglais doublent le L, en américain on double le L si l'accent porte sur la 2e syllabe  

ex: travelled/traveled, travelling/traveling, traveller/traveler  

Attention ! To excel et to propel (et leurs dérivés) prennent toujours deux L.  

## Past simple

Certains verbes sont réguliers en américain et prennent un -ed au passé simple, alors qu"en britanique ils sont irréguliers et prennent un -t.  

ex: dreamt/dreamed, learnt/learned, spelt/spelled, burnt/burned  

## Get

UK: get, got, got  
US: get, got, gotten  

## Prépositions

Le temps (at/on) :  
UK: at the weekend  
US: on the weekend  

## have got (UK) vs have (US)

UK: I have got  
US: I have  

## as (UK)/like (US)

UK: I felt as if I was talking to a stranger. As I told you.  
US: I felt like I was talking to a stranger. Like I told you.  

## Les dates

UK: le jour en 1er  
US: le mois en 1er  

ex:  
UK: 4th April à l'écrit, généralement prononcé the fourth of April  
US: April 4th prononcé tel quel, ou parfois April the fourth.  

## Les contractions

Certaines formes contractées sont beaucoup plus fréquentes en anglais américain. Elles sont très familières et ne s'emploient que dans la langue parlée (et dans les chansons). Mais il faut savoir les reconnaitre.  

ex (US):  
wanna = want to  
gonna = going to  
gotta = have got to (ou have to)  
