---
title: "Intégration continue"
author: "Vincyane Badouard"
date: "15/01/2021"
output: html_document
---

Intégration continue = confier à un service externe certaines taches (tests, production de docs, tricot) pour limiter la perte de temps.


# Travis
1) nécessaire d’ouvrir un compte sur le site
2) possible de s’authentifier avec son compte GitHub

Lien Travis-github :  
clé privée PAT (Personal Access Token)
Créer un jeton : Settings > Developer settings > Personal access tokens > Generate new token > décrire "Travis" et donner l'autorisation "repo" > Generate token et *enregistrer le jeton qqpart, sinon c'est perdu*.

Mon jeton déjà créé : 2c731e9c305bb450d691bdea233ede3e7f7b1d88 *a ne pas perdre*

Activation du dépôt:
Sur le site de Travis > settings > settings du repository > Name : GITHUB_TOKEN, Value : <coller le jeton> > add
La liste des dépôts GitHub est présentée.
Pour en activer un, cliquer sur l’interrupteur gris à côté de son nom

## Script de contrôle de Travis
fichier: .travis.yml.


# Codecov

Evalue la proportion testé du code
1) nécessaire d’ouvrir un compte sur le site
2) possible de s’authentifier avec son compte GitHub
